#!/bin/sh

if [ -z "$SHITTP_CONFIG_DIR" ]; then
  SHITTP_CONFIG_DIR="${XDG_CONFIG_HOME:=$HOME/.local/config}/shittp"
fi

cleanup() {
  [ -d "$tar_tmpdir" ] && rm -rf "$tar_tmpdir"
}

msg() {
  IFS=" $IFS"
  set -- '%s\n' "${*:-}"
  IFS=${IFS#?}
  printf "$@"
}

die() {
  msg "$1"
  exit "${2:-1}"
}

trap cleanup EXIT

if [ ! -d "$SHITTP_CONFIG_DIR" ]; then
  die "Configuration directory [ $SHITTP_CONFIG_DIR ] is required"
fi

tar_tmpdir=$(mktemp --directory)
cp -R "$SHITTP_CONFIG_DIR" "$tar_tmpdir"

cat <<'EOF' >"$tar_tmpdir/shittp/__shittp_setup"
trap 'rm -rf "$SHITTP_HOME"' EXIT

if [ -e "$SHITTP_HOME/.vimrc" ]; then
  export VIMINIT="source $SHITTP_HOME/.vimrc"
fi

case $SHELL in
  *bash*)
    if [ -e "$SHITTP_HOME/.bashrc" ]; then
      bash --init-file "$SHITTP_HOME/.bashrc"
    else
      bash -i
    fi
  ;;
  *) sh -i ;;
esac
EOF

archive_build_script=$(tar czf - -C "$tar_tmpdir/shittp" . | base64 | awk '
BEGIN { print "archive=" }
{ print "archive=\"${archive}" $0 "\\n\"" }
')

remote_command="$archive_build_script"'
tmpdir=$(mktemp --directory)
printf "$archive" | base64 --decode | tar zxf - -C "$tmpdir"
export SHITTP_HOME=$tmpdir
. "$SHITTP_HOME/__shittp_setup"
'

ssh -t -o RemoteCommand="$remote_command" "$@"
